# Generated by Django 3.0.4 on 2020-04-02 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('B2B', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='primary_contact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='B2B.Person'),
        ),
    ]
