# Generated by Django 3.0.4 on 2020-04-02 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('B2B', '0002_company_primary_contact'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='company',
            table='Companies',
        ),
    ]
