# Generated by Django 3.0.4 on 2020-04-05 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('B2B', '0003_auto_20200402_1428'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name_plural': 'Companies'},
        ),
        migrations.AlterModelTable(
            name='company',
            table=None,
        ),
    ]
