# Generated by Django 3.0.4 on 2020-04-05 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('B2B', '0004_auto_20200405_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='wants_ab',
            field=models.BooleanField(verbose_name='Needs results from Audiobooks.com?'),
        ),
        migrations.AlterField(
            model_name='company',
            name='wants_gb',
            field=models.BooleanField(verbose_name='Needs search results from Google Books?'),
        ),
        migrations.AlterField(
            model_name='company',
            name='wants_kb',
            field=models.BooleanField(verbose_name='Needs search results from Kobo?'),
        ),
        migrations.AlterField(
            model_name='company',
            name='wants_lc',
            field=models.BooleanField(verbose_name='Needs search results from Livraria Cultura?'),
        ),
        migrations.AlterField(
            model_name='company',
            name='wants_sd',
            field=models.BooleanField(verbose_name='Needs results from Scribd?'),
        ),
        migrations.AlterField(
            model_name='company',
            name='wants_tb',
            field=models.BooleanField(verbose_name='Needs search results from Test Bookstore?'),
        ),
    ]
