# Generated by Django 3.0.4 on 2020-04-05 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('B2B', '0007_auto_20200405_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='wants_ab',
            field=models.BooleanField(verbose_name='Audiobooks.com'),
        ),
        migrations.AlterField(
            model_name='company',
            name='wants_gb',
            field=models.BooleanField(verbose_name='Google Books'),
        ),
        migrations.AlterField(
            model_name='company',
            name='wants_kb',
            field=models.BooleanField(verbose_name='Kobo'),
        ),
        migrations.AlterField(
            model_name='company',
            name='wants_lc',
            field=models.BooleanField(verbose_name='Livraria Cultura'),
        ),
        migrations.AlterField(
            model_name='company',
            name='wants_sd',
            field=models.BooleanField(verbose_name='Scribd'),
        ),
        migrations.AlterField(
            model_name='company',
            name='wants_tb',
            field=models.BooleanField(verbose_name='Test Bookstore (for TESTING purposes ONLY)'),
        ),
    ]
