# Generated by Django 3.0.4 on 2020-04-10 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('B2B', '0008_auto_20200405_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='primary_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='B2B.Person'),
        ),
    ]
