# Generated by Django 3.0.4 on 2020-04-10 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('B2B', '0009_auto_20200410_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
